version: '3'
services:
  nginx:
    restart: always
    image: nginx:1.13
    ports:
     - "80:80"
    volumes:
     - ./app:/usr/share/nginx/html:ro
     - ./nginx.conf:/etc/nginx/nginx.conf
  selenium-hub:
    image: selenium/hub
    container_name: selenium-hub
    ports:
      - "4444:4444"
  # integration:
  #   image: node
  #   depends_on:
  #     - selenium-hub
  #   volumes:
  #     - ./integration:/app/src
  #   environment:
  #     - DOCKER_MACHINE_IP=192.168.99.100
  chrome:
    image: selenium/node-chrome
    depends_on:
      - selenium-hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium-hub
      - HUB_PORT_4444_TCP_PORT=4444
      - HUB_HOST=selenium-hub
    expose:
      - "5555"
    volumes:
      - /dev/shm:/dev/shm # Mitigates the Chromium issue described at https://code.google.com/p/chromium/issues/detail?id=519952
    # firefox:
  #   image: selenium/node-firefox
  #   depends_on:
  #     - selenium-hub
  #   environment:
  #     - HUB_PORT_4444_TCP_ADDR=selenium-hub
  #     - HUB_PORT_4444_TCP_PORT=4444
  #     - HUB_HOST=selenium-hub